---

- name: copy github ssh key
  copy:
    src: "config/ccc_key.pem"
    dest: /home/ubuntu/.ssh/ccc_key
    owner: ubuntu
    group: ubuntu
    mode: 0600


- name: configure ssh to use ansible key for github.com
  template:
    src: "config/ssh_config"
    dest: /home/ubuntu/.ssh/config
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Creates remote working directory
  file:
    path: '{{ remote_working_directory }}'
    state: directory
    mode: 0755

- name: git clone
  shell: git clone git@github.com:yunfeijing/ccc-p2.git --config core.sshCommand="ssh -i /home/ubuntu/.ssh/ccc_key"
  args:
    chdir: '{{ remote_working_directory }}'
