---
ansible_user: ubuntu
remote_working_directory: /home/ubuntu/COMP90024
git_repo: /home/ubuntu/COMP90024/ccc-p2
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
ansible_ssh_private_key_file: "config/mrc_key.pem"

### Couchdb ###
couchdb_image: ibmcom/couchdb3:latest
couchdb_user: admin
couchdb_pass: admin
couchdb_VERSION: "3.1.1"
couchdb_cookie: "a192aeb9904e6590849337933b000c99"
couchdb_uuid: "a192aeb9904e6590849337933b001159"
cluster_name: "_cluster_setup"
couchdb_container_name: "couchdb_"
couchdb_port: 5984
#couchdb_db_name: "live-tweets"

proxy_env:
  HTTP_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  HTTPS_PROXY: http://wwwproxy.unimelb.edu.au:8000/
  http_proxy: http://wwwproxy.unimelb.edu.au:8000/
  https_proxy: http://wwwproxy.unimelb.edu.au:8000/
  no_proxy: localhost, 127.0.0.1, localaddress, 172.16.0.0/12, .melbourne.rc.nectar.org.au, .storage.unimelb.edu.au, .cloud.unimelb.edu.au
