---
#############################################
#                 CouchDB                   #
#############################################
couchdb_image: ibmcom/couchdb3:latest
couchdb_user: admin
couchdb_pass: admin
couchdb_VERSION: "3.1.1"
couchdb_cookie: "a192aeb9904e6590849337933b000c99"
couchdb_uuid: "a192aeb9904e6590849337933b001159"
cluster_name: "_cluster_setup"
couchdb_container_name: "couchdb_"
couchdb_port: 5984
couchdb_db_name: "live-tweets"
#############################################
#                  Docker                   #
#############################################
enable_docker_remote_control: true
