---
# Ubuntu20的软件地址
- name: Add specified repository into sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: deb http://cz.archive.ubuntu.com/ubuntu focal main 
    state: present

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
  
- name: curl command
  become: yes
  apt_key:
    url: https://couchdb.apache.org/repo/bintray-pubkey.asc
    state: present

- name: echo command
  become: yes
  shell: echo "deb https://apache.bintray.com/couchdb-deb focal main" \
    | sudo tee /etc/apt/sources.list.d/couchdb.list

- name: install couchdb
  become: yes
  retries: 5
  delay: 4
  apt:
    name: couchdb
    state: latest
    update_cache: yes

- name: change owner of couchdb executable
  file:
    state: file
    mode: 0770
    owner: couchdb
    group: couchdb
    path: /usr/bin/couchdb
  when: couchdb_install.changed

- name: copy the couchdb folder to /usr/local/lib/
  become: yes
  shell: cp -r /opt/couchdb /usr/local/lib

- name: apply the cluster configuration
  become: yes
  copy: src=/home/ubuntu/COMP90024/ccc-p2/ansible/roles/couchdb-clusters/cluster.local.ini dest=/usr/local/lib/couchdb/etc/local.ini
  when: configure_cluster == True

- name: install the sysv script to run CouchDB as a service
  become: yes
  copy: src=/home/ubuntu/COMP90024/ccc-p2/ansible/roles/couchdb-clusters/couchdb dest=/etc/init.d/couchdb mode=0755

- name: start CouchDB and ensure it is enabled at boot time
  become: yes
  service: name=couchdb state=started enabled=yes

- name: check that we can ping CouchDB on all its ports
  become: yes
  uri: url=http://127.0.0.1:{{ item }}
  with_items:
  - 5986
  - 5984