---
# Ubuntu20的软件地址
- name: Add specified repository into sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: deb http://cz.archive.ubuntu.com/ubuntu focal main 
    state: present

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
  
- name: curl command
  become: yes
  apt_key:
    url: https://couchdb.apache.org/repo/bintray-pubkey.asc
    state: present

- name: echo command
  become: yes
  shell: echo "deb https://apache.bintray.com/couchdb-deb focal main" \
    | sudo tee /etc/apt/sources.list.d/couchdb.list

- name: install couchdb
  become: yes
  retries: 5
  delay: 4
  apt:
    name: couchdb
    state: latest
    update_cache: yes

# - name: create the database directory
#   become: yes
#   file:
#     state: directory
#     path: '{{ database_dir }}'
#     mode: '777'