---
# Ubuntu16的软件地址
- name: Add specified repository into sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: deb http://security.ubuntu.com/ubuntu xenial-security main
    state: present

# Ubuntu18的软件地址
- name: Add specified repository into sources list
  become: yes
  ansible.builtin.apt_repository:
    repo: deb http://cz.archive.ubuntu.com/ubuntu bionic main 
    state: present

- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install couchdb dependencies
  become: yes
  apt:
    name: ['libicu55', 'libcurl3', 'libssl1.0.0', 'libffi6']
    state: latest
    install_recommends: no 
    update_cache: yes

# - name: Install couchdb dependencies
#   become: yes
#   apt:
#     name: ['pkg-config','erlang','build-essential','libicu-dev','libcurl4-openssl-dev','apt-transport-https', 'build-essential', 'ca-certificates', 'python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common', 'unzip', 'vim']
#     state: latest
#     install_recommends: no 
#     update_cache: yes

- name: Install couchdb dependencies
  become: yes
  apt:
    deb="/home/ubuntu/COMP90024/ccc-p2/ansible/couch-libmozjs185.deb"
  
- name: Install couchdb dependencies
  become: yes
  apt:
    name: ['curl'] # 安装curl会和上边的libcurl3冲突，但是神奇的是这两个都需要，网上应该有一些解决办法，就差这一步了
    state: latest
    install_recommends: no 
    update_cache: yes
  
- name: curl command
  become: yes
  apt_key:
    url: https://couchdb.apache.org/repo/bintray-pubkey.asc
    state: present

- name: echo command
  become: yes
  shell: echo "deb https://apache.bintray.com/couchdb-deb bionic main" | sudo tee -a /etc/apt/sources.list

- name: install couchdb
  become: yes
  retries: 5
  delay: 4
  apt:
    name: couchdb
    state: latest
    update_cache: yes

# - name: create the database directory
#   become: yes
#   file:
#     state: directory
#     path: '{{ database_dir }}'
#     mode: '777'