---
- hosts: instances

  vars_files:
    - host_vars/config.yaml
  gather_facts: true

  roles:
    - role: add-proxy
    - role: install-dependencies
    - role: clone-github-rep
    - role: mount-volume
