# version: '3'

# services:

#     backend:
#         restart: always
#         build: 
#             dockerfile: Dockerfile
#             context: ./backend
#         image: "backend"
#         environment:
#             APP_SERVER_PORT: 8000
#             COUCHDB_HOST: http://admin:admin@172.26.132.83:5984
#         volumes: 
#             - /app/node_modules
#             - ./backend:/app
#         ports:
#             - '8000:8000'

#     frontend:
#         container_name: frontend
#         image: "frontend"
#         build: 
#             dockerfile: Dockerfile
#             context: ./frontend
#         environment:
#             REACT_APP_PORT: 4000
#         # volumes:
#         #     - '.:/app'
#         #     - '/app/node_modules'
#         ports:
#             - '4000:4000'
#         # links:
#         #     - backend

#     nginx:
#         restart: always
#         image: "nginx"
#         build:
#             dockerfile: Dockerfile
#             context: ./nginx
#         ports:
#             - '80:80'
version: '3'

services:

    backend:
        build: ./backend
        environment:
            APP_SERVER_PORT: 8000
            COUCHDB_HOST: http://admin:admin@172.26.132.83:5984
        ports:
            - 8000:8000
        command: npm run start


    frontend:
        build: ./frontend
        environment:
            REACT_APP_PORT: 4000
        ports:
            - 80:4000
        stdin_open: true
        links:
            - backend
        command: serve -p 4000 -s .