version: '3'

services:

    backend:
        build: ./backend
        image: "backend"
        environment:
            APP_SERVER_PORT: 8000
            COUCHDB_HOST: http://admin:admin@172.26.132.83:5984
        networks:
            - ccc-network

    frontend:
        build: ./frontend
        image: "frontend"
        environment:
            REACT_APP_PORT: 4000
        networks:
            - ccc-network

    revproxy:
        build: ./nginx
        image: "nginx"
        networks:
            - ccc-network
        ports:
            - "80:80"

networks:
    ccc-network: