version: '3'

services:

    backend:
        build: ./backend
        environment:
            APP_SERVER_PORT: 8000
            COUCHDB_HOST: http://admin:admin@172.26.132.83:5984
        ports:
            - "8000:8000"
        command: npm run start

    frontend:
        build: ./frontend
        environment:
            REACT_APP_PORT: 4000
        ports:
            - "80:80"
        stdin_open: true
